### ISSUE TITLE
Anyscale Image 

### ISSUE THREAD

**Issue by harsh-goglocal** [ray-project/ray-llm#78]
In the aviary cluster yaml file , 
image used is `anyscale/aviary:test`
should it be changed to `anyscale/ray-llm:latest`

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: aviary-deploy

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    cache_stopped_nodes: False
docker:
    image: "anyscale/aviary:test"            #### --
    image: "anyscale/ray-llm:latest"            #### ++
    container_name: "aviary"
    run_options:
      - --entrypoint ""
```
